language: php

# Which PHP versions we want to test
php:
  - nightly
  - 5.6
  - 5.5
  - 5.4

# Which versions are allowed to fail
matrix:
  allow_failures:
    - php: nightly
    - php: 5.6
    - php: 5.5

# Which branches we want to test
branches:
  only:
    - master
    - develop
    - /^release-.*$/

before_install:
  - composer selfupdate

install:
  - composer install

after_script:
  - ./vendor/bin/test-reporter
